/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sintatico;

import java.util.List;
import javax.swing.DefaultListModel;
import lexico.Token;

/**
 *
 * @author yago
 */
public class Tela extends javax.swing.JFrame {
    
    public List<Token> listT;

    /**
     * Creates new form Tela
     * @param listT
     */
    public Tela(List<Token> listT) {
        this.listT = listT;
        initComponents();
        DefaultListModel dim = new DefaultListModel();
        for(Token i : listT){
            dim.addElement(i.toString());
        }
        this.listaTokens.setModel(dim);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        afd = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaTokens = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaOps = new javax.swing.JList<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        afd.setBackground(new java.awt.Color(80, 63, 47));
        afd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sintatico/AfdBottomUp.jpg"))); // NOI18N
        afd.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        afd.setMaximumSize(new java.awt.Dimension(200, 150));
        afd.setPreferredSize(new java.awt.Dimension(200, 150));
        add(afd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 290));

        listaTokens.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaTokens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaTokensMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaTokens);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 370, 290));

        listaOps.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaOps);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 90, 290));
    }// </editor-fold>//GEN-END:initComponents

    private void listaTokensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaTokensMouseClicked
        Token esse = this.listT.get(listaTokens.getAnchorSelectionIndex());
        DefaultListModel dim = new DefaultListModel();
        for(String s : esse.getOperacoes()){
            dim.addElement(s);
        }
        this.listaOps.setModel(dim);
    }//GEN-LAST:event_listaTokensMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel afd;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaOps;
    private javax.swing.JList<String> listaTokens;
    // End of variables declaration//GEN-END:variables
}
